### ISSUE TITLE
Random movement seems not quite random in JS version

### ISSUE THREAD

**Issue by catseye** [catseye/noit-o-mnain-worb#1]
Bobule movement is clearly *mostly* random, but they seem to like to move northwest more than they like to move southeast, based on observing e.g. freefill at high speed many times -- the north and west walls certainly seem to get more high-pressure black areas against them than the south and east walls do.

(Also, note to self: there is something wrong where the example programs using `(` and `)` instead of `<` and `>` to avoid having to escape HTML aren't being translated to one-ways in the playfield.)

**Comment by cpressey** [comment]
Finally found and fixed.  The problem was not with the random number generation (although it might not be perfectly uniform in Firefox, or indeed any given browser,) it was with the fact that we were sometimes moving one bobule twice (or even more) on the same step, by virtue of the fact that the foreach loop would change the position of the bobule, perhaps to the right or down or down and to the right, and that bobule would get processed again when the foreach got to that position.

Verily!  Closing.
